### PR TITLE
Fix tutorial04 API 

### LINKED ISSUE #480: tutorial data and script are outdated
1. the example data are outdated. For example, `https://github.com/openforcefield/openff-evaluator/blob/1e1a2d06e5a01d0f3262518a648996314fdb8276/openff/evaluator/data/tutorials/tutorial02/estimated_data_set.json#L241` here `openff.evaluator.utils.statistics` no longer exists
2. `https://github.com/openforcefield/openff-evaluator/blob/main/docs/tutorials/tutorial04.ipynb` this script uses some old api of `openff-evaluator` and `openff-toolkit` and no longer works.

### PR DESCRIPTION
**Pull request by wenyan4work**
## Description
update api of tutorial04, partially resolves #480 
forcebalance 1.9.4 doesn't work properly with evaluator 0.4.1, so this fix sticks to 1.9.3+0.3.9 

## Todos
None

## Questions
None

## Status
- [x] Ready to go

### CODE REVIEW

**Comment by mattwthompson** [comment]
I will try to finally take a look at this next week. Could you confirm my understanding that this relies on running simulations, i.e. should be run on a cluster or workstation with access to GPU compute?

**Comment by mattwthompson** [comment]
Curious - does 1.9.5 make this all work again?

**Comment by wenyan4work** [comment]
> I will try to finally take a look at this next week. Could you confirm my understanding that this relies on running simulations, i.e. should be run on a cluster or workstation with access to GPU compute?

It runs on my windows 11 laptop running cuda inside WSL-2. I believe it should run on any standard linux + cuda workstation.

I didn't try the DaskJobQueueBackend because I have no access to that type of resources.

The latest commits has been validated with a fresh install of openff-toolkit 0.12 + evalutor 0.4.2 + forcebalance 1.9.5

**Comment by wenyan4work** [comment]
> Curious - does 1.9.5 make this all work again?

Yes, it works now... I was editing my comment and your comment popped up at exactly the same moment :)

**Comment by mattwthompson** [comment]
Excellent, hope to have some time this week to once this over and think about how it should be deployed. Not sure if a new patch release is in order.

**Comment by mattwthompson** [comment]
@wenyan4work were you able to get the simulations in the latter part of tutorial 2 working? I won't ask you to run them to completion but I'm curious if they were able to start without error and if it seemed like they were actually using your laptop's hardware (especially if you have a discrete GPU)

**Comment by wenyan4work** [comment]
I did run all tutorials to completion (openmm7.7) and the gpu on my laptop
is utilized. The simulation in the tutorial includes HVap, where the gas
phase is always on cpu so you may see the gpu idle for sometime during the
simulation.

**Comment by mattwthompson** [comment]
Could you upload the JSON files that are written out at the end of each of the tutorials?

**Comment by mattwthompson** [comment]
Okay - I finally got CUDA up and running on my Windows box so they're churning along. If you have the files handy and feel like sharing I'd still like to use them to double-check mine, but I'm not asking you to re-run the simulations on my account.

**Comment by mattwthompson** [comment]
Thanks for your contribution! It is included in #499 with some other housekeeping.

**Pull request closed without merging**
