### PR TITLE
Compatibility with OpenFF Toolkit v0.11.0

### PR DESCRIPTION
**Pull request by mattwthompson**
## Description
This PR updates code and tests to be compatible with the [changes coming](https://openforcefield.atlassian.net/wiki/spaces/IN/pages/2217443329/Topology+Biopolymer+Refactor+Release) in a new version of the toolkit.

## Todos
Notable points that this PR has either accomplished or will accomplish.
  - [x] pAPRika tests
  - [x] Yank tests
  - [x] Install checkmol
  - [ ] Update docstrings

## Questions
- [ ] Question1

## Status
- [ ] Ready to go

### CODE REVIEW

**Comment by mattwthompson** [comment]
The current failures are

1. **Linting** - Black's update last month included some significant changes, which I included in #423 to make this PR easier to review.
2. **Yank** - The tracebacks imply either something is broken in Yank in a way that does not seem related to changes here.

**Comment by j-wags** [comment]
Let's put this back to WIP - Until we have a release candidate package for OFF Toolkit 0.11.0, out there, we won't be sure when this is stable enough for review.

**Comment by mattwthompson** [comment]
I discovered a possible regression in the toolkit that's doing funky things here, including causes at least one test (`openff/evaluator/tests/test_utils/test_packmol.py::test_packmol_paracetamol`) to fail: https://github.com/openforcefield/openff-toolkit/issues/1307

**Comment by mattwthompson** [comment]
I should look into using OpenMM for writing this PDB File as it would bypass the weird behavior with `OpenEyeToolkitWrapper.to_file`; https://github.com/openforcefield/openff-toolkit/issues/1307 is much too thorny to resolve in one sweep (https://github.com/openforcefield/openff-toolkit/pull/1309 was a mess).

**Comment by mattwthompson** [comment]
https://github.com/openforcefield/openff-interchange/pull/467

**Comment by mattwthompson** [comment]
I'm not fixing the docs builds here.  #457

**Pull request merged**
