### PR TITLE
OpenFF theme for docs

### PR DESCRIPTION
**Pull request by Yoshanuikabundi**
## Description
Switch to the OpenFF theme for documentation

Looks like API docs have not been rendering [since v3.9.0](https://docs.openforcefield.org/projects/evaluator/en/v0.3.10/api.html). This was due to openff.units being unavailable in RTD and is fixed in this PR.

## Todos
Notable points that this PR has either accomplished or will accomplish.
  - [x] New theme
  - [x] 404 page
  - [x] Mambaforge in RTD builds
  - [x] Fix API docs not being rendered

## Questions
None so far

## Status
- [x] Ready to go

### CODE REVIEW

**Comment by mattwthompson** [comment]
> Looks like API docs have not been rendering

This project's `master` branch is in a half-broken state due to me merging #399 and other API breaks long before the toolkit was ready to provide them in releases.

In any case, I skimmed a few pages and things look good to me except for the API docs not being rendered on the PR build. But I recall the API docs not being built in other packages' PR builds even when they're fine on the normal builds. I can't find a recent example of this, having checked a few places ... have you seen this happen?

Either way, I don't see that as a blocker. Switching themes is an improvement and fixing the API docs can be done later.

**Comment by Yoshanuikabundi** [comment]
Fixed the API docs. 3.10 added a dependency on openff-units, but it was neither mocked in Sphinx nor included in the RTD environment. Adding it to the RTD environment fixed it (though I needed to clear cache to see the updated API page)

I'll merge this once I get an approving review :)

**Review by mattwthompson — APPROVED** [review]
[I see API docs!](https://openff-docs--446.org.readthedocs.build/projects/evaluator/en/446/api/generated/openff.evaluator.properties.Density.html#openff.evaluator.properties.Density)

**Comment by Yoshanuikabundi** [comment]
> But I recall the API docs not being built in other packages' PR builds even when they're fine on the normal builds. I can't find a recent example of this, having checked a few places ... have you seen this happen?

I have never seen this but I believe you! In this case the API docs are broken in the [last] [several] releases though.

[last]: https://docs.openforcefield.org/projects/evaluator/en/v0.3.11/api.html
[several]: https://docs.openforcefield.org/projects/evaluator/en/v0.3.10/api.html

**Pull request merged**
